/content/drive/MyDrive/research_discourse_relation/discourse_relation_explainability
num_added_tokens: 16, added_special_tokens: <NOUN>,<PRONOUN>,<ADJECTIVAL-NOUN>,<PRENOUN-ADJECTIVAL>,<ADVERB>,<CONJUNCTION>,<INTERJECTION>,<VERB>,<ADJECTIVE>,<AUXILIARY-VERB>,<PARTICLE>,<PREFIX>,<SUFFIX>,<SYMBOL>,<AUXILIARY-SYMBOL>,<BLANK>
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at cl-tohoku/bert-base-japanese-v3 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|          | 0/11 [00:00<?, ?it/s]/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
loss: 0.065260   	accuracy: 0.2575 	precision: 0.1848 	recall: 0.2304 	f1: 0.1233
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING] WON'T CONVERT resume_in_forward /usr/local/lib/python3.10/dist-packages/transformers/models/bert/modeling_bert.py line 1562
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING] due to:
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING] Traceback (most recent call last):
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 727, in _convert_frame
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     result = inner_convert(frame, cache_entry, hooks, frame_state)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     compiled_product = _compile(
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 646, in _compile
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     guarded_code = compile_inner(code, one_graph, hooks, transform)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 562, in compile_inner
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     out_code = transform_code_object(code, transform)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     transformations(instructions, code_options)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 151, in _fn
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     return fn(*args, **kwargs)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 527, in transform
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     tracer.run()
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2128, in run
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     super().run()
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 818, in run
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     and self.step()
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 781, in step
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     getattr(self, inst.opname)(inst)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2243, in RETURN_VALUE
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     self.output.compile_subgraph(
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 945, in compile_subgraph
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/lib/python3.10/contextlib.py", line 79, in inner
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     return func(*args, **kwds)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1087, in compile_and_call_fx_graph
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     compiled_fn = self.call_user_compiler(gm)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1159, in call_user_compiler
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1140, in call_user_compiler
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     compiled_fn = compiler_fn(gm, self.example_inputs())
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     compiled_gm = compiler_fn(gm, example_inputs)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 1668, in __call__
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     return compile_fx(model_, inputs_, config_patches=self.config)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 1168, in compile_fx
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     return aot_autograd(
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/backends/common.py", line 55, in compiler_fn
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     cg = aot_module_simplified(gm, example_inputs, **kwargs)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 887, in aot_module_simplified
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     compiled_fn = create_aot_dispatcher_function(
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 600, in create_aot_dispatcher_function
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 425, in aot_wrapper_dedupe
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 630, in aot_wrapper_synthetic_base
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 97, in aot_dispatch_base
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     compiled_fw = compiler(fw_module, updated_flat_args)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 1100, in fw_compiler_base
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     return inner_compile(
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     inner_compiled_fn = compiler_fn(gm, example_inputs)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/debug.py", line 305, in inner
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     return fn(*args, **kwargs)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/lib/python3.10/contextlib.py", line 79, in inner
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     return func(*args, **kwds)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 320, in compile_fx_inner
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     compiled_graph = fx_codegen_and_compile(
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 550, in fx_codegen_and_compile
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     compiled_fn = graph.compile_to_fn()
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/graph.py", line 1116, in compile_to_fn
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     return self.compile_to_module().call
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/graph.py", line 1070, in compile_to_module
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     mod = PyCodeCache.load_by_key_path(
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 1892, in load_by_key_path
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     exec(code, mod.__dict__, mod.__dict__)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/tmp/torchinductor_root/rx/crxybthtpddsziwurmr4u5rd232l6bnycy4zbqj4awclxvk2micc.py", line 28, in <module>
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     triton_red_fused__log_softmax_nll_loss_forward_0 = async_compile.triton('triton_', '''
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 2448, in triton
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     future = self.process_pool().submit(
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/lib/python3.10/concurrent/futures/process.py", line 720, in submit
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     raise BrokenProcessPool(self._broken)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING] torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING] BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING] Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING] Traceback (most recent call last):
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 727, in _convert_frame
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     result = inner_convert(frame, cache_entry, hooks, frame_state)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     compiled_product = _compile(
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 646, in _compile
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     guarded_code = compile_inner(code, one_graph, hooks, transform)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 562, in compile_inner
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     out_code = transform_code_object(code, transform)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     transformations(instructions, code_options)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 151, in _fn
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     return fn(*args, **kwargs)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 527, in transform
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     tracer.run()
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2128, in run
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     super().run()
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 818, in run
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     and self.step()
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 781, in step
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     getattr(self, inst.opname)(inst)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2243, in RETURN_VALUE
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     self.output.compile_subgraph(
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 945, in compile_subgraph
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/lib/python3.10/contextlib.py", line 79, in inner
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     return func(*args, **kwds)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1087, in compile_and_call_fx_graph
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     compiled_fn = self.call_user_compiler(gm)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1159, in call_user_compiler
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1140, in call_user_compiler
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     compiled_fn = compiler_fn(gm, self.example_inputs())
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     compiled_gm = compiler_fn(gm, example_inputs)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 1668, in __call__
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     return compile_fx(model_, inputs_, config_patches=self.config)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 1168, in compile_fx
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     return aot_autograd(
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/backends/common.py", line 55, in compiler_fn
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     cg = aot_module_simplified(gm, example_inputs, **kwargs)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 887, in aot_module_simplified
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     compiled_fn = create_aot_dispatcher_function(
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 600, in create_aot_dispatcher_function
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 425, in aot_wrapper_dedupe
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 630, in aot_wrapper_synthetic_base
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 97, in aot_dispatch_base
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     compiled_fw = compiler(fw_module, updated_flat_args)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 1100, in fw_compiler_base
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     return inner_compile(
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     inner_compiled_fn = compiler_fn(gm, example_inputs)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/debug.py", line 305, in inner
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     return fn(*args, **kwargs)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/lib/python3.10/contextlib.py", line 79, in inner
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     return func(*args, **kwds)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 320, in compile_fx_inner
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     compiled_graph = fx_codegen_and_compile(
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 550, in fx_codegen_and_compile
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     compiled_fn = graph.compile_to_fn()
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/graph.py", line 1116, in compile_to_fn
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     return self.compile_to_module().call
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/graph.py", line 1070, in compile_to_module
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     mod = PyCodeCache.load_by_key_path(
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 1892, in load_by_key_path
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     exec(code, mod.__dict__, mod.__dict__)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/tmp/torchinductor_root/rx/crxybthtpddsziwurmr4u5rd232l6bnycy4zbqj4awclxvk2micc.py", line 28, in <module>
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     triton_red_fused__log_softmax_nll_loss_forward_0 = async_compile.triton('triton_', '''
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 2448, in triton
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     future = self.process_pool().submit(
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]   File "/usr/lib/python3.10/concurrent/futures/process.py", line 720, in submit
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]     raise BrokenProcessPool(self._broken)
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING] torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING] BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING] Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
[2024-05-12 08:30:02,423] torch._dynamo.convert_frame: [WARNING]
  0%|          | 0/1 [00:00<?, ?it/s] /usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()[00:00<?, ?it/s]
/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py:411: UserWarning: Error detected in AddmmBackward0. Traceback of forward call that caused the error:
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/bert/modeling_bert.py", line 1539, in forward
    outputs = self.bert(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/bert/modeling_bert.py", line 988, in forward
    encoder_outputs = self.encoder(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/bert/modeling_bert.py", line 582, in forward
    layer_outputs = layer_module(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/bert/modeling_bert.py", line 472, in forward
    self_attention_outputs = self.attention(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/bert/modeling_bert.py", line 411, in forward
    attention_output = self.output(self_outputs[0], hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/bert/modeling_bert.py", line 361, in forward
    hidden_states = self.dense(hidden_states)
 (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:113.)
  result = Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  0%|          | 0/1 [00:24<?, ?it/s]
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/research_discourse_relation/discourse_relation_explainability
/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link
/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link
/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link
/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link
/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link
/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link
Requirement already satisfied: typed-argument-parser in /usr/local/lib/python3.10/dist-packages (1.10.0)
Requirement already satisfied: typing-inspect>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from typed-argument-parser) (0.9.0)
Requirement already satisfied: docstring-parser>=0.15 in /usr/local/lib/python3.10/dist-packages (from typed-argument-parser) (0.16)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from typing-inspect>=0.7.1->typed-argument-parser) (1.0.0)
Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.10/dist-packages (from typing-inspect>=0.7.1->typed-argument-parser) (4.11.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.40.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.14.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.20.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.25.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (24.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2023.12.25)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.31.0)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.19.1)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.66.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers) (2023.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2024.2.2)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.10/dist-packages (0.1.99)
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (2023.4)
Requirement already satisfied: fugashi[unidic-lite] in /usr/local/lib/python3.10/dist-packages (1.3.2)
Requirement already satisfied: unidic-lite in /usr/local/lib/python3.10/dist-packages (from fugashi[unidic-lite]) (1.0.8)
Requirement already satisfied: wandb in /usr/local/lib/python3.10/dist-packages (0.17.0)
Requirement already satisfied: click!=8.0.0,>=7.1 in /usr/local/lib/python3.10/dist-packages (from wandb) (8.1.7)
Requirement already satisfied: docker-pycreds>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (0.4.0)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (3.1.43)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.10/dist-packages (from wandb) (4.2.1)
Requirement already satisfied: protobuf!=4.21.0,<5,>=3.19.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (3.20.3)
Requirement already satisfied: psutil>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from wandb) (6.0.1)
Requirement already satisfied: requests<3,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (2.31.0)
Requirement already satisfied: sentry-sdk>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (2.1.1)
Requirement already satisfied: setproctitle in /usr/local/lib/python3.10/dist-packages (from wandb) (1.3.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from wandb) (67.7.2)
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from docker-pycreds>=0.4.0->wandb) (1.16.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.11)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.0.0->wandb) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.0.0->wandb) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.0.0->wandb) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.0.0->wandb) (2024.2.2)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (5.0.1)
[34m[1mwandb[39m[22m: [33mWARNING[39m Calling wandb.login() after wandb.init() has no effect.